homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 47.070162
  longitude: 15.422686
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 300
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Vienna

  customize:
    # Only the 'entity_id' is required.  All other options are optional.
    sensor.yr_symbol:
      friendly_name: Weather
    sensor.yr_temperature:
      friendly_name: Temperature
    sensor.yr_pressure:
      friendly_name: Pressure
    sensor.yr_humidity:
      friendly_name: Humidity

mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: home
  username: home
  password: home123

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Sensors
sensor:
  - platform: yr
    monitored_conditions:
      - temperature
      - symbol
      - pressure
      - humidity
  - platform: mqtt
    state_topic: "home/temperature1"
    name: "temperature1"
    friendly_name: "Temperature"
    unit_of_measurement: "°C"
  - platform: mqtt
    state_topic: "home/temperature2"
    friendly_name: "Temperature"
    name: "temperature2"
    unit_of_measurement: "°C"
  - platform: mqtt
    state_topic: "home/temperature3"
    friendly_name: "Temperature"
    name: "temperature3"
    unit_of_measurement: "°C"
  - platform: mqtt
    state_topic: "home/humidity1"
    friendly_name: "Humidity"
    name: "humidity1"
    unit_of_measurement: "%"
  - platform: mqtt
    state_topic: "home/humidity2"
    friendly_name: "Humidity"
    name: "humidity2"
    unit_of_measurement: "%"
  - platform: mqtt
    state_topic: "home/humidity3"
    friendly_name: "Humidity"
    name: "humidity3"
    unit_of_measurement: "%"
  - platform: mqtt
    state_topic: "home/vbat1"
    friendly_name: "Battery"
    name: "vbat1"
    unit_of_measurement: "V"
  - platform: mqtt
    state_topic: "home/vbat2"
    friendly_name: "Battery"
    name: "vbat2"
    unit_of_measurement: "V"
  - platform: mqtt
    state_topic: "home/vbat3"
    friendly_name: "Battery"
    name: "vbat3"
    unit_of_measurement: "V"

switch:
  - platform: mqtt
    command_topic: "home/plug1"
    state_topic: "home/plug1"
    name: "TV back light"
    retain: true
  - platform: mqtt
    command_topic: "home/plug2"
    state_topic: "home/plug2"
    name: "Desk lamp"
    retain: true


# Text to speech
tts:
  platform: google


group:
## Views
  living_room_view:
    view: yes
    name: Living room
    entities:
      - group.living_room
  bed_room_view:
    view: yes
    name: Bed room
    entities:
      - group.bed_room
  piotr_room_view:
    view: yes
    name: Piotr room
    entities:
      - group.piotr_room
  outside_view:
    view: yes
    name: Outside
    entities:
      - group.outside
## Groups
  living_room:
    name: Living room
    entities:
      - sensor.temperature2
      - sensor.humidity2
      - sensor.vbat2
      - switch.tv_back_light
      - switch.desk_lamp
      - media_player.tv

  bed_room:
    name: Bed room
    entities:
      - sensor.humidity1
      - sensor.temperature1
      - sensor.vbat1

  piotr_room:
    name: Piotr room
    entities:
      - sensor.humidity3
      - sensor.temperature3
      - sensor.vbat3

  outside:
    name: Outside
    entities:
      - sensor.yr_symbol
      - sensor.yr_temperature
      - sensor.yr_pressure
      - sensor.yr_humidity
      - sun.sun

#device_tracker:
#  - platform: nmap_tracker
#    hosts: 192.168.0.1/24

