homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 47.070162
  longitude: 15.422686
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 300
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Vienna

  customize:
    # Only the 'entity_id' is required.  All other options are optional.
    - entity_id: sensor.yr_symbol
      friendly_name: Weather
    - entity_id: sensor.yr_temperature
      friendly_name: Temperature
    - entity_id: sensor.yr_pressure
      friendly_name: Pressure
    - entity_id: sensor.yr_humidity
      friendly_name: Humidity

mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: home
  username: home
  password: home123

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Sensors
sensor:
  - platform: yr
    monitored_conditions:
      - temperature
      - symbol
      - pressure
      - humidity
  - platform: mqtt
    state_topic: "home/temperature1"
    name: "Temperature"
    unit_of_measurement: "°C"
  - platform: mqtt
    state_topic: "home/temperature2"
    name: "Temperature"
    unit_of_measurement: "°C"
  - platform: mqtt
    state_topic: "home/humidity1"
    name: "Humidity"
    unit_of_measurement: "%"
  - platform: mqtt
    state_topic: "home/humidity2"
    name: "Humidity"
    unit_of_measurement: "%"
  - platform: mqtt
    state_topic: "home/vbat1"
    name: "Battery"
    unit_of_measurement: "V"
  - platform: mqtt
    state_topic: "home/vbat2"
    name: "Battery"
    unit_of_measurement: "V"

switch:
  - platform: mqtt
    command_topic: "home/plug1"
    name: "TV back light"
    retain: true


# Text to speech
tts:
  platform: google


group:
  default_view:
    view: no
    entities:
      - group.living_room
      - group.outside
  living_room:
    name: Living room
    view: yes
    entities:
      - sensor.humidity_2
      - sensor.temperature_2
      - sensor.battery_2
      - switch.tv_back_light
      - media_player.tv
  outside:
    name: Outside
    view: yes
    entities:
      - sensor.yr_symbol
      - sensor.yr_temperature
      - sensor.yr_pressure
      - sensor.yr_humidity

